### ISSUE TITLE
"GET /static/base.css HTTP/1.1" 304 0

### ISSUE THREAD

**Issue by N74NK** [ShehanAT/fitness-forum#1]
Why does my web look like this, what's wrong?
![Screenshot1](https://nyvt1.000webhostapp.com/Screenshot_2020-04-10-23-37-06.png)
> And this is what my terminal shows
![Screenshot2](https://nyvt1.000webhostapp.com/Screenshot_2020-04-10-23-40-20.png)

**Comment by ShehanAT** [comment]
The links you provided are not working. Could you provide some new links?

**Comment by ShehanAT** [comment]
Closing link due to lack of response.
